language: cpp

matrix:
  fast_finish: true
  include:
    - os: linux
      compiler: gcc
      env: BUILD_TYPE=Release
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
            - gcc-9
      script: sudo bash ./ci/linux.sh
    - os: linux
      compiler: gcc
      env: BUILD_TYPE=Debug
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
            - gcc-9
      script: sudo bash ./ci/linux.sh
    - os: linux
      compiler: gcc
      env: BUILD_TYPE=Release
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - gcc-8
      script: sudo bash ./ci/linux.sh
    - os: linux
      compiler: gcc
      env: BUILD_TYPE=Debug
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - gcc-8
      script: sudo bash ./ci/linux.sh
    
script: sudo bash ./ci/build.sh

notifications:
  email:
    recipients:
      - asharnrus.info@gmail.com
    on_success: never
    on_failure: change