language: cpp

matrix:
  fast_finish: true
  include:
    - os: linux
      compiler: gcc
      env:
        - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"
        - BUILD_TYPE=Release
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
            - gcc-9
      before_install: 
        - eval "${MATRIX_EVAL}"
      script:
        - ./ci/linux.sh
    - os: linux
      compiler: gcc
      env:
        - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"
        - BUILD_TYPE=Debug
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
            - gcc-9
      before_install: 
        - eval "${MATRIX_EVAL}"
      script:
        - ./ci/linux.sh
    - os: linux
      compiler: gcc
      env:
        - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"
        - BUILD_TYPE=Release
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - gcc-8
      before_install: 
        - eval "${MATRIX_EVAL}"
      script:
        - ./ci/linux.sh
    - os: linux
      compiler: gcc
      env:
        - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"
        - BUILD_TYPE=Debug
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - gcc-8
      before_install: 
        - eval "${MATRIX_EVAL}"
      script:
        - ./ci/linux.sh
    

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty
    packages:
      - g++-9
      - gcc-9
      - clang-9

notifications:
  email:
    recipients:
      - asharnrus.info@gmail.com
    on_success: never
    on_failure: change