language: cpp

matrix:
  fast_finish: true
  include:
    ##### Linux
    ### GCC
    - os: linux
      compiler: gcc
      env: BUILD_TYPE=Release
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
            - gcc-9
      script: sudo bash ./ci/linux.sh
    - os: linux
      compiler: gcc
      env: BUILD_TYPE=Release
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - gcc-8
      script: sudo bash ./ci/linux.sh
    - os: linux
      compiler: gcc
      env: BUILD_TYPE=Release
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - gcc-7
      script: sudo bash ./ci/linux.sh
    ### Clang
    - os: linux
      compiler: clang
      env: BUILD_TYPE=Release
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-8
          packages:
            - clang-8
      script: sudo bash ./ci/linux.sh
    - os: linux
      compiler: clang
      env: BUILD_TYPE=Release
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-7
          packages:
            - clang-7
      script: sudo bash ./ci/linux.sh

notifications:
  email:
    recipients:
      - asharnrus.info@gmail.com
    on_success: never
    on_failure: change