language: cpp

matrix:
  fast_finish: true
  include:
    - os: linux
      compiler: gcc
      env:
        - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"
        - BUILD_TYPE=Release
        - CMAKE_DIR="/opt/cmake/bin"
      before_install: 
        - eval "${MATRIX_EVAL}"
        # Get newest cmake
        - sudo wget "https://github.com/Kitware/CMake/releases/download/v3.16.0-rc3/cmake-3.16.0-rc3-Linux-x86_64.tar.gz"
        - sudo tar -xzf cmake-3.16.0-rc3-Linux-x86_64.tar.gz
        - sudo mv cmake-3.16.0-rc3-Linux-x86_64 /opt/cmake
        # Compile googletest
        - sudo wget https://github.com/google/googletest/archive/release-1.10.0.tar.gz
        - sudo tar -xzf release-1.10.0.tar.gz
        - cd googletest-release-1.10.0
        - sudo mkdir install 
        - sudo mkdir build 
        - cd build
        - sudo ${CMAKE_DIR}/cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_INSTALL_PREFIX="/usr/src/gtest"
        - sudo ${CMAKE_DIR}/cmake --build .
        - sudo ${CMAKE_DIR}/cmake --install .
        - cd "${TRAVIS_BUILD_DIR}"
      before_script:
        - sudo mkdir build
        - cd build
      script:
        - sudo ${CMAKE_DIR}/cmake .. -Dtravis-test_BUILD_TESTS=ON -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DGTest_DIR="/usr/src/gtest/lib/cmake/GTest"
        - sudo ${CMAKE_DIR}/cmake --build .
        - sudo ${CMAKE_DIR}/ctest --verbose

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty
    packages:
      - g++-9
      - gcc-9
      - clang-9
      - make

notifications:
  recipients:
    - asharnrus.info@gmail.com
  email:
    on_success: never
    on_failure: change